import { FormField } from "./models";

export const defaultFields = {
  anoLetivo: {
    type: "select",
    value: [],
    name: "anoLetivo",
    label: "Ano Letivo",
    placeholder: "Selecione",
    validators: ["required"],
    options: [
      { hash: "2024", descricao: "2024" },
      { hash: "2025", descricao: "2025" },
    ],
  },
  redesDePagamento: {
    type: "multiselect",
    value: [],
    name: "redesPagamento",
    label: "Redes de Pagamento",
    placeholder: "Selecione a rede de pagamento",
    validators: ["required"],
    options: [
      { hash: "mat", descricao: "Matemática" },
      { hash: "por", descricao: "Português" },
      { hash: "cie", descricao: "Ciências" },
      { hash: "his", descricao: "História" },
      { hash: "geo", descricao: "Geografia" },
      { hash: "ing", descricao: "Inglês" },
      { hash: "edf", descricao: "Educação Física" },
      { hash: "art", descricao: "Artes" },
    ],
  },
  descricao: {
    type: "textarea",
    value: "",
    name: "descricao",
    label: "Descrição",
    placeholder: "Digite a descrição",
    validators: ["required", "minLength:10", "maxLength:300"],
    max: 300,
  },

  pontosOcorrencia: {
    type: "number",
    value: "",
    name: "pontos",
    label: "Pontuação",
    min: 0,
    max: 100,
    validators: ["required", "min:0", "max:100"],
  },
  redes: {
    type: "select",
    value: "",
    name: "redes",
    label: "Redes",
    placeholder: "Selecione",
    validators: ["required"],
    options: [
      { hash: "001", descricao: "Rede Municipal" },
      { hash: "002", descricao: "Rede Estadual" },
      { hash: "003", descricao: "Rede Federal" },
    ],
  },

  series: {
    type: "select",
    value: "",
    name: "series",
    label: "Séries",
    placeholder: "Selecione",
    validators: ["required"],
    options: [
      { hash: "001", descricao: "Rede Municipal" },
      { hash: "002", descricao: "Rede Estadual" },
      { hash: "003", descricao: "Rede Federal" },
    ],
  },
  nomeAluno: {
    type: "text",
    value: "",
    name: "nomeAluno",
    label: "Nome do Aluno",
    placeholder: "Digite o nome completo",
    validators: ["required", "minLength:2", "maxLength:100"],
  },
  turno: {
    type: "select",
    value: "",
    name: "turno",
    label: "Turno de Estudo",
    placeholder: "Qual turno você estuda?",
    validators: ["required"],
    options: [
      { hash: "matutino", descricao: "Matutino (7h às 12h)" },
      { hash: "vespertino", descricao: "Vespertino (13h às 18h)" },
      { hash: "noturno", descricao: "Noturno (19h às 23h)" },
      { hash: "integral", descricao: "Período Integral" },
    ],
  },
  email: {
    type: "text",
    value: "",
    name: "email",
    label: "Email",
    placeholder: "Digite seu email",
    validators: ["required", "email"],
  },
  telefone: {
    type: "text",
    value: "",
    name: "telefone",
    label: "Telefone",
    placeholder: "(11) 99999-9999",
    validators: [
      "required",
      "pattern:^\\([0-9]{2}\\)\\s[0-9]{4,5}-[0-9]{4}$",
    ],
  },
  cpf: {
    type: "text",
    value: "",
    name: "cpf",
    label: "CPF",
    placeholder: "000.000.000-00",
    validators: [
      "required",
      "pattern:^[0-9]{3}\\.[0-9]{3}\\.[0-9]{3}-[0-9]{2}$",
    ],
  },
  idade: {
    type: "number",
    value: "",
    name: "idade",
    label: "Idade",
    placeholder: "Digite sua idade",
    validators: ["required", "min:0", "max:120"],
    min: 0,
    max: 120,
  },
  disciplinas: {
    type: "multiselect",
    value: [],
    name: "disciplinas",
    label: "Disciplinas",
    placeholder: "Selecione as disciplinas",
    validators: ["required"],
    options: [
      { hash: "mat", descricao: "Matemática" },
      { hash: "por", descricao: "Português" },
      { hash: "cie", descricao: "Ciências" },
      { hash: "his", descricao: "História" },
      { hash: "geo", descricao: "Geografia" },
      { hash: "ing", descricao: "Inglês" },
      { hash: "edf", descricao: "Educação Física" },
      { hash: "art", descricao: "Artes" },
    ],
  },

}
